#pragma once
#include <canard.h>
#include <stdbool.h>
#include <stdint.h>
#include <common/uavcan.h>

#include <canard/uavcan.equipment.ice.reciprocating.CylinderStatus.h>

#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_MAX_PACK_SIZE 196
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_DT_SIG 0xD38AA3EE75537EC6
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_DT_ID 1120

#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_STATE_STOPPED 0
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_STATE_STARTING 1
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_STATE_RUNNING 2
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_STATE_FAULT 3
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_GENERAL_ERROR 1
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_CRANKSHAFT_SENSOR_ERROR_SUPPORTED 2
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_CRANKSHAFT_SENSOR_ERROR 4
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_TEMPERATURE_SUPPORTED 8
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_TEMPERATURE_BELOW_NOMINAL 16
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_TEMPERATURE_ABOVE_NOMINAL 32
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_TEMPERATURE_OVERHEATING 64
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_TEMPERATURE_EGT_ABOVE_NOMINAL 128
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_FUEL_PRESSURE_SUPPORTED 256
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_FUEL_PRESSURE_BELOW_NOMINAL 512
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_FUEL_PRESSURE_ABOVE_NOMINAL 1024
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_DETONATION_SUPPORTED 2048
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_DETONATION_OBSERVED 4096
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_MISFIRE_SUPPORTED 8192
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_MISFIRE_OBSERVED 16384
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_OIL_PRESSURE_SUPPORTED 32768
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_OIL_PRESSURE_BELOW_NOMINAL 65536
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_OIL_PRESSURE_ABOVE_NOMINAL 131072
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_DEBRIS_SUPPORTED 262144
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_FLAG_DEBRIS_DETECTED 524288
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_SPARK_PLUG_SINGLE 0
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_SPARK_PLUG_FIRST_ACTIVE 1
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_SPARK_PLUG_SECOND_ACTIVE 2
#define UAVCAN_EQUIPMENT_ICE_RECIPROCATING_STATUS_SPARK_PLUG_BOTH_ACTIVE 3

struct uavcan_equipment_ice_reciprocating_Status_s {
    uint8_t state;
    uint32_t flags;
    uint8_t engine_load_percent;
    uint32_t engine_speed_rpm;
    float spark_dwell_time_ms;
    float atmospheric_pressure_kpa;
    float intake_manifold_pressure_kpa;
    float intake_manifold_temperature;
    float coolant_temperature;
    float oil_pressure;
    float oil_temperature;
    float fuel_pressure;
    float fuel_consumption_rate_cm3pm;
    float estimated_consumed_fuel_volume_cm3;
    uint8_t throttle_position_percent;
    uint8_t ecu_index;
    uint8_t spark_plug_usage;
    struct {uint8_t cylinder_status_len; struct uavcan_equipment_ice_reciprocating_CylinderStatus_s cylinder_status[16];};
};

extern const struct uavcan_message_descriptor_s uavcan_equipment_ice_reciprocating_Status_descriptor;

uint32_t encode_uavcan_equipment_ice_reciprocating_Status(struct uavcan_equipment_ice_reciprocating_Status_s* msg, uint8_t* buffer);
uint32_t decode_uavcan_equipment_ice_reciprocating_Status(const CanardRxTransfer* transfer, struct uavcan_equipment_ice_reciprocating_Status_s* msg);
void _encode_uavcan_equipment_ice_reciprocating_Status(uint8_t* buffer, uint32_t* bit_ofs, struct uavcan_equipment_ice_reciprocating_Status_s* msg, bool tao);
void _decode_uavcan_equipment_ice_reciprocating_Status(const CanardRxTransfer* transfer, uint32_t* bit_ofs, struct uavcan_equipment_ice_reciprocating_Status_s* msg, bool tao);
